version: '3'
services:
  hub:
    image: cmccauley/iot:0.0.1
    ports:
     - "8080:8080"
    links:
     - mqtt   
  
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto/config:/mosquitto/config
      - ./mqtt/mosquitto/data:/mosquitto/data
    links:
     - db
     
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme